apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: your-org-ui-lib
  annotations:
    github.com/project-slug: pats/nextjs-monorepo-example
  tags:
    - library
    - nodejs
    - frontend
spec:
  type: library
  owner: null
  lifecycle: production
  system: nextjs-monorepo-example
